### ISSUE TITLE
Upload .pbtxt file

### ISSUE THREAD

**Issue by SwagJ** [CR-Ko/MegaDepth_Tensorflow#3]
Hi, 

Thank you very much for your work. Is that possible for you to upload .pbtxt file as well? Since tensorflow have changed to 2.0 and our class use tf 2.0 as well. I just need that to convert your pretrained model in tf2.0. Thank you very much!

**Comment by kkk324** [comment]
Please see the new commits. Thank to @supernlogn 's contribution.  
He convert megadepth model from tf1 version to Keras version, as well as tf2 version. 

And I'm really curious about how you guys use this model on your project.

**Comment by SwagJ** [comment]
yes, I have generated .pbtxt after pulling your repo. This is my teammate. 
We try to use depth map for feature detection and description.
