### ISSUE TITLE
Always getting the same depth result when running tflite inference

### ISSUE THREAD

**Issue by wpmed92** [CR-Ko/MegaDepth_Tensorflow#5]
I made the following steps to get a tflite model:

**1. Froze session:**
`output_graph_def = tf.compat.v1.graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(["module/div_1"] 
    ) 
    with tf.compat.v1.gfile.GFile("megadepth.pb", "wb") as f:
        f.write(output_graph_def.SerializeToString())`

**2. Converted inference graph to tflite:**

` 
    
    def convert(): 
    converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
        graph_def_file='megadepth.pb',
        input_arrays=['Placeholder'],
        input_shapes={'Placeholder' : [1, 240, 320, 3]},
        output_arrays=['module/div_1']
    )
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_model = converter.convert()

    with open('model.tflite', 'wb') as f:
        f.write(tflite_model)
`

**3. Ran inference on Android using implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'**

I used the model which includes pre and post processing. No matter what image I give the model, it always produces the exact same gradient grayscale image, very similar (or maybe the same) as reported here: https://github.com/zhengqili/MegaDepth/issues/8 
<img width="318" alt="Screenshot 2020-11-17 at 11 23 25" src="https://user-images.githubusercontent.com/8374618/99378169-6a2eff80-28c7-11eb-801d-53ce55a3eeb3.png">

You wrote that you successfully ran inference on both iOS and Android. What tflite version did you try it with?

**Comment by wpmed92** [comment]
I managed to solve it. The problem was that I was passing empty image data to the model, I didn't put my pixels from the Bitmap to the ByteBuffer.

**Comment by kkk324** [comment]
Cool!
